### ISSUE TITLE
sjp.int() doesn't work with plm model

### ISSUE THREAD

**Issue by zyevelyn** [sjPlot/devel#114]
The error message is "no applicable method for 'family' applied to an object of class c('plm', 'panelmodel'). sjp.lm() works great.

**Comment by sjPlot** [comment]
I could solve this issue inside sjPlot, but the nature of this issue should be solved in the plm-package, which should provide base methods like `family`, `model.matrix` etc.

**Comment by zyevelyn** [comment]
Could you please let me know when you fix it? Also does type = "eff" work for 'plm?' Thank you so much!

**Comment by sjPlot** [comment]
For sjp.int, it should work now. `type = "eff"` should also work for `plm`. Just fixed it in the latest commit: https://github.com/sjPlot/devel/commit/340df38984a8f2c7afdde5e44f7962d7b846f30a

**Comment by helix123** [comment]
There is a `model.matrix` method for class `plm`, no `family` method though. The only sense making thing could be to return the same as for family.lm, i.e. use `gaussian()` because plm models are estimated by `lm` on (quasi-)demeaned data. `model.response` is `pmodel.response` in plm.
 Any other functions missing for `plm`?

**Comment by sjPlot** [comment]
I'm not sure. `gls`, `plm`, `pggls` all vary in their generic function support. `gls` does not provide se and p-values when calling `coef(summary(fit))`, `lme` does not support `family` and so on... I always have to try out these things for each class / type of model... This makes it so difficult to write tidier, e.g. `broom` does also not support all of those models.
