### ISSUE TITLE
sjp.lmer axis modification codes

### ISSUE THREAD

**Issue by npalt123** [sjPlot/devel#126]
Hello, thank you for developing this R package.

I am plotting using the sjp.lmer with type = "fe.pred" and I want to change both the Y axis limits and the X & Y axis titles.  I am using the following code however it is not producing any results:

sjp.lmer(modelNumber, 
         type = "fe.pred",
         showScatterPlot = FALSE, 
         axisLimits.y = c(0,12),
         axisTitle.x="NEWTITLE",
         axisTitle.y="NEWTITLE")

The above code produces the same graph as this code - 

sjp.lmer(modelNumber, 
         type = "fe.pred",
         showScatterPlot = FALSE)

I am not sure if there is some other thing that needs to be turned "on" to get the axis codes to work?

Thank you!

**Comment by sjPlot** [comment]
The problem is, that, depending on the amount of predictors you have changing axis titles for each plots. That's why `axisTitle` is not supported by `type = "fe.pred"`. However, in [this commit](https://github.com/sjPlot/devel/commit/859ff63476fa4b67aa8a1a2eb7a0476b764746f0) I added support for the `axisLimits.y` argument (which is, however, now names `ylim`).

So, this will be supported in the forthcoming update. But this update will most likely break existing code, as I changed a lot of argument names to get a more consistent arguments style in my package, across all functions.

**Comment by norberello** [comment]
Thanks for this cool library, but have the axis limit possibilities been updated? I cannot yet find an easy way of putting the limits of Y axis. 

The probs I want to see are too small for the Y axis limits that are automatically given:
![image](https://user-images.githubusercontent.com/28672268/34334876-a6091ab4-e94a-11e7-8720-97318700c4c6.png)
