### ISSUE TITLE
Exporting graphes

### ISSUE THREAD

**Issue by atuofa** [sjPlot/devel#134]
Is there a way to improve graph resolution by incorporating "dpi" into sjp.setTheme? When i used the save_plot function it definitely improve the resolution of the graph but some features of the graph are lost. e.g. tick marks. I will like to keep tick marks and all other features of my graph when using the save_plot function. Please kindly let me know if this is possible

**Comment by sjPlot** [comment]
`save_plot` is just a small wrapper for `ggplot2::ggsave`, with some defaults that I thought that might be useful, and `save_plot` also has a `dpi` argument. `setTheme` just sets the theme appearance and has nothing to do with the plot resolution, so that would not be appropriate to add a `dpi` argument there.

So, you either can use `dpi` in `save_plot`, or you can use `ggplot2::ggsave`.

**Comment by atuofa** [comment]
Thank you, this was very helpful!
