### ISSUE TITLE
sjp.corr Labels Colors

### ISSUE THREAD

**Issue by fabioand2k** [sjPlot/devel#154]
Hi Daniel,

i read documentation but i cant find how can i change colors of labels in correlation plot.

when i use Tile type, it will be usefull, 'cause its confusion to read text inside tiles.

thanks

**Comment by sjPlot** [comment]
I had to make some revisions due to the forthcoming ggplot2-update, and `sjp.corr()` was also affected. Labels are now only in black color, and I had to remove the circle-type. Maybe this will be re-integrated later, but for now I have to make my package work with ggplot. If you like, you can check the current github-version of sjPlot.

**Comment by fabioand2k** [comment]
thanks!
