### ISSUE TITLE
understanding of implemented PCA + rotation methods

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#191]
Hi, 
I just noticed that you introduced rotation options for the PCA methods in the package, but I'm not quite sure which procedures are actually used. Isn't rotation usually used for factor analysis, which is similar but nevertheless not equivalent to PCA?
Edit: To clarify this a bit more: I guess in the context of this package, the methods are rather used for testing models about latent factors rather than for simple dimensionality reduction right? Or maybe for both? Maybe it would therefore be useful to support both, factor analysis as well as PCA?

Edit2: In this context I like [this thread](http://stats.stackexchange.com/questions/1576/what-are-the-differences-between-factor-analysis-and-principal-component-analysi) which also includes related literature.

**Comment by sjPlot** [comment]
See this thread: http://stats.stackexchange.com/questions/612/is-pca-followed-by-a-rotation-such-as-varimax-still-pca

sjp.pca (and sjt.pca) uses `stats::prcomp()`, which is a PCA. Rotating the factor loadings afterwards is quite common for PCA. In my experience, in social sciences mostly varimax is used, because components are not correlated. However, sometimes they are, and in such cases mostly oblimin is used. That's why I implemented that method, because we just had such a case in one of our papers we wrote.

Factor analysis is more often used in psychology, less in sociology - at least that is my impression. That's why I haven't implemented FA in my package yet. I only implement those methods (or support for those models) I actually work with, because I'm no statistician and only learn methods "when needed" - and if I'm not familiar with a method, I'm trying to avoid implementation in my package die to the lack of understanding, which may lead to inappropriate or even wrong implementation.

Let me give you an example in which situations we use PCA. We included the FaBel (http://www.rki.de/SharedDocs/Publikationen/DE/2001/R/Ravens-Sieberer_U04.html?cms_abstrakt=true) in one survey, and finally had three dimensions (two of them being "social impact" and "financial burden"). We used these scores in regression models, as shown in this paper: https://www.ncbi.nlm.nih.gov/pubmed/26100508

**Comment by methodds** [comment]
Thanks for the clarification on the methods and the examples. Its always interesting to see other social science applications but also potentially regional (?) variations in the use of statistical methods: The sociologists in Bamberg mostly rely on factor analysis :)
I totally see your point of not implementing methods for which one does not have a deep understanding, I'm no statistician either.

I guess this can be closed.
