### ISSUE TITLE
Question regarding the new tidyverse friendly syntax

### ISSUE THREAD

**Issue by methodds** [sjPlot/devel#211]
Hi,

as it currently stands there is no way to use functions like ``rec()`` and ```set_na()``` without explicitly using the corresponding parameters ``recodes`` and ``value`` (for which either "na" or "values" might perhaps be a better name) right?

In earlier versions it was possible to do something like ```v1 <- rec(d$q155a, '3=1')```, which does not work anymore. 

Edit: If this is the case, I'd like to suggest using one common parameter, like "vals" or some other **short** keyword, for all the data manipulation functions like ``rec()``, ``set_na``, ``set_label``, ``set_labels()``, etc. The intuition is that the function name itself also states what the function does and there is no need for the corresponding "main" parameter to also have specific name. This would make it easier for users as they would only have to remember one keyword as the most important parameter for all these functions.

Or is there any other way to use the functions as in earlier versions, without having to explicitly state the "main" parameters?

**Comment by methodds** [comment]
Just to give you an example for why the new syntax is a little bit annoying, consider this code block:

```
cdu <- rec(d$q119a, '1:3=1; else=0')
staerke <- rec(d$q120, '1=5;2=4;3=3;4=2;5=1;-97=0')
d$cdu_pid <- cdu * staerke %>%  set_label('PID CDU/CSU') %>% set_labels(
  c('keine PID' = 0, 'starke PID' = 5))

d$krise_merkel <- rec(d$q39, '1=5 [sehr zufrieden];
                      2=4 [zufrieden]; 3=3 [teils/teils];
                      4=2 [unzufrieden]; 5=1[sehr unzufrieden]',
                      var.label= 'Zufriedenheit Merkel mit Umgang Schuldenkrise')

d %>% select(q21a, cdu_pid, krise_merkel) %>% set_na(-99:-71) %>% frq()
```
I think this is easily readable and short enough with the "old" syntax, whereas the new syntax would require quite a number of additional keywords, ``recodes=``, ``labs=``, ``value=``, etc.

**Comment by sjPlot** [comment]
I'm not quite sure what your exact request is right now. ;-)

> Or is there any other way to use the functions as in earlier versions, without having to explicitly state the "main" parameters?

No, because of the `...`-ellipses-argument, which requires further arguments to be explicitly named. I could add an alias-argument, so that the "main" arguments always have the same name (but still the old one is working, so you can either use `values = "1=5 [sehr zufrieden];"` or `recodes = "1=5 [sehr zufrieden];"`).

**Comment by sjPlot** [comment]
I think this issue belongs to sjmisc-pkg.

**Comment by methodds** [comment]
Ye sry, that's actually sjmisc. I think the alias would a good solution, although as a lazy person I'm still a little bit sad =D But I guess the ellipsis changes totally make sense for the package philosophy

**Comment by sjPlot** [comment]
Yes, explicitly naming arguments is a drawback when using ellipses to allow an arbitrary number of variable-arguments to the function. However, with auto-completion, there shouldn't be much more effort to write the code ;-)

What function-arguments could be more consistent? for `set_na()`, you suggested using `na` instead of `value`, which makes sense to me, but wouldn't fit for other functions, of course.

**Comment by methodds** [comment]
I mostly use the following functions (and could imagine these are most important for other users too):
- rec --> "recodes="
- set_na--> "value="
- set_label --> "lab="
- set_labels --> "labels="

What do you think about simply using "rec, na, label and labels" as function arguments? These are basically equivalent to the function names and it should be very easy for new users to get used to that. The same logic could be applied to other sjmisc functions. Following this convention, an alias might not even be necessary at all.
