### ISSUE TITLE
sjp.glmer with unscaled x axis

### ISSUE THREAD

**Issue by aurielfournier** [sjPlot/devel#224]
Hello,

I'm really enjoying much of the functionality of this package, but I am wondering if there is a way to plot a generalized mixed model that contains scaled variables with sjp.glmer with an unscaled x axis. 

reprex example here: 

```
library(sjPlot)
library(sjmisc)
library(lme4)
# load sample data set.
data(efc)

efc$scale_c12hour <- scale(efc$c12hour)
efc$scale_e15reat <- scale(efc$e15relat)

m <- glmer(c175empl ~ scale_c12hour + scale_e15reat + (1|resttotn), data=efc, family=binomial(link = "logit"))

sjp.glmer(m, type="fe.pc", show.ci=TRUE)
# what I would like to do is have this plot, but the x axis be the actual variables, not the scaled variables

```
Thank you!

**Comment by sjPlot** [comment]
The only way to this is to tweak the plot-output afterwards. You just need to know the range of your variable.

```
library(ggplot2)
p <- sjp.glmer(m, type = "fe.slope", show.ci = TRUE)
p$plot + scale_x_continuous(breaks = seq(-1, 3, by = 1), labels = c(0, 20, 40, 60, 80))
```

However, since - in this case - both variables have a different range, faceting is not recommended, because you have the same axis for both facets then. In such cases, use

```
p <- sjp.glmer(m, type = "fe.slope", show.ci = TRUE, facet.grid = F)
p$plot.list[[1]] + scale_x_continuous(breaks = seq(-1, 3, by = 1), labels = c(0, 20, 40, 60, 80))
p$plot.list[[2]] + scale_x_continuous(breaks = seq(-1, 3, by = 1), labels = c(0, 3, 6, 9, 12))
```

Note that `type = "fe.slope"` _does not_ adjust for covariates. If you want that, use `type = "pred.fe"` or `type = "eff"`.

**Comment by sjPlot** [comment]
also, note that `scale()` returns a matrix. Better use `sjmisc::std()` or `sjmisc::center()` to get vectors back.
