### ISSUE TITLE
Non-incremental levels and labels

### ISSUE THREAD

**Issue by BERENZ** [sjPlot/devel#44]
Variables in my dataset do not have incremental levels (e.g. 1, 2, 5, 15, 20, 35, 99) therefore, I have problems with obtaining the right result in `sjt.*` functions. 

Please find example code for clarification below

```{r}
library(sjPlot)

### example data
example_data <- data.frame(labelled(
  c(10,20,30,10,20,30,10,99,30,20),
  c('c'=10,'b'=20,'a'=30,'NA'=99)))

names(example_data) <- 'V1'

## incorrect result (only first group is visible)
sjt.frq(example_data$V1) 

## correct results (however without labels)
sjt.frq(as.numeric(example_data$V1)) 
```

**Comment by sjPlot** [comment]
I guess it is the same issue as https://github.com/sjPlot/devel/issues/2
I'm adressing this issue for the next update.

**Comment by BERENZ** [comment]
Thanks! When do you plan to release new version?

**Comment by sjPlot** [comment]
Usually, I try to update regularly without much delays. As you can [see here](http://cran.r-project.org/src/contrib/Archive/sjPlot/), the package is almost updated monthly. However, the CRAN-maintainers appreciate not too short update-cycles due to the workload.

Perhaps the next CRAN-update will be in July, however, if this issue is fixed, you can also always install the GitHub-Version (you'll be faster up-to-date then).
