### ISSUE TITLE
R CMD check fails with dev version of tidyr

### ISSUE THREAD

**Issue by hadley** [sjPlot/devel#62]
```
checking whether package ‘sjPlot’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import by ‘tidyr::%>%’ when loading ‘sjPlot’
  Warning: replacing previous import by ‘tidyr::replace_na’ when loading ‘sjPlot’
See ‘/private/tmp/Rtmp5nYH93/check_cranb673158d7feb/sjPlot.Rcheck/00install.out’ for details.
```
probably because you have too many unqualified imports

**Comment by sjPlot** [comment]
What does the 2nd warning exactly mean?
I have a function call `varCount.ci <- sjmisc::replace_na(varCount, max(varCount, na.rm = T) + 1)` and use `@import sjmisc`.

And according to the first warning: Do I have to import magrittr? Or what might be the reason for that it?

**Comment by sjPlot** [comment]
I use three times `tidyr::gather`, but `@import tidyr`. Would it be better to replace it with `@importFrom tidyr gather`?

**Comment by sjPlot** [comment]
The current dev of sjPlot successfully passes CRAN check with current R devel and tidyr dev (tested on Win 10). I hope this closes this issue...

What would be the next step required for you to submit tidyr to CRAN?

**Comment by hadley** [comment]
The next step is waiting two weeks to give every time to fix their packages and submit updates to CRAN :)

**Comment by sjPlot** [comment]
Yes, I thought something like that ;-)

I have a small problem, what would you suggest how to handle it?

The current dev of the `sjPlot` package depends on some (not many) new function of the `sjmisc` package, which I also maintain. The dev of the `sjmisc` package facilitates the new missing structure (`is_na` attribute) of your `haven` package, so the current dev of `sjmisc` won't pass checks without a new update from `haven`.

Possible solutions:
1) I wait with submission of the `sjPlot` package, until a new `haven` package is submitted to CRAN (thus, what would happen if I do not submit fixes for `tidyr` within the next two weeks)?
2) You submit a new update of `haven` to CRAN within the next days ;-D
3) I revert the changes made to `sjPlot` that depend on new functions of `sjmisc`, and only submit `sjPlot` to CRAN
4) I copy your code for the labelled constructor that includes the `is_na` attribute, so examples and functions of `sjmisc` will work, assuming (hoping) that the `haven` package will keep this structure of labelled vectors, and submit `sjmisc` and `sjPlot` to CRAN within the next days (both packages are ready for submission, I'm just waiting for a `haven` update, but if I have an own labelled constructor in my package, identical to yours, it would work as well)

Any other suggestions?

**Comment by hadley** [comment]
I'm unlikely to get a haven update out in the next two weeks, but I will be working on in the next couple of months. You don't have to submit a new version to CRAN: you'll probably get some angry emails from the CRAN maintainers though, and it might cause problems for people using your package.

I think 3) is probably your best bet. You can use conditional statements based on package versions, e.g. `if (packageVersion("haven") >= "0.3"), to make sure the code works with both dev and released versions. That's what I do when I want to make a change that breaks one of my own packages.  I think 4) would also work, but might require a bit more work on your side when I release haven.

**Comment by sjPlot** [comment]
Ok, I'll go for 4) and provide an own `labelled` function / constructor for labelled class objects, in case someone wants to use the multiple missing feature (`is_na` attribute) right now. This seems to me the option with the least work (option 3) requires changing all cross references in the documentation as well, which seems to be more work, especially since I'm not familiar with versioning to create a new branch from sjPlot 1.8.2 that only fixes the tidyr issues).

**Comment by hadley** [comment]
Oh, I just realised there's an option 5): figure out what I changed that broke sjPlot (I'm pretty sure it was incidental) and either tell me or make a PR. Then you can do a release of sjPlot at a more natural time.

**Comment by sjPlot** [comment]
Well, I used `@import tidyr`, and I also use `@import sjmisc`. From the `sjmisc`-package, I'm calling the `replace_na` function. A function with the same name is also in your tidyr-update. I now changed to selective imports using `@importFrom tidyr gather`, which eleminated both warnings.

I guess, the pipe-warning is due to your implementation of the magrittr-pipe-operator, which was also caused due to my complete import of `tidyr`.

**Comment by sjPlot** [comment]
Since the warnings only stem from the examples, where I call a deprecated function (`get_val_labels`), which is now renamed in the `sjmisc` package to `get_labels`, I guess I simply remove the `.Deprecated` calls and add them in a later update, hence allowing both `get_val_labels` and `get_labels` for some time ;-)
