### ISSUE TITLE
non-integer #successes in a binomial glm

### ISSUE THREAD

**Issue by mattjerhart** [sjPlot/devel#64]
When I run the following code:
```R
color_model = glmer(correct~cond_trial_num_scale*iscolor + (1|subjID) + (1|stimuli) + (1|location),data=all_data, family=binomial(link="logit"))
sjp.glmer(color_model,
          type = "fe.prob",
          show.se = TRUE,
          facet.grid = FALSE)
```
I get this warning with may be causing a silent error:
Warning messages:
1: In eval(expr, envir, enclos) :
  non-integer #successes in a binomial glm!
2: In eval(expr, envir, enclos) :
  non-integer #successes in a binomial glm!

And, only one of the two iscolor levels are plotted. facet.grid set to true will show two plots, but I'm not sure what they represent since their isn't a legend. I would like to plot the predicted probability correct of both levels of iscolor as a function of cond_trial_num_scale. I would like the legend to say color and not color. Any suggestions on how to product this sort of plot?

**Comment by sjPlot** [comment]
The warning is due to the model-fit and not related to the `sjPlot` package. see [here](http://stackoverflow.com/questions/12953045/warning-non-integer-successes-in-a-binomial-glm-survey-packages) or [here](http://stats.stackexchange.com/questions/87956/r-lme4-how-to-apply-binomial-glm-to-percentages-rather-than-yes-no-counts).

According to your other problem: I need to know more about the data to understand what's happening and being able to help you. Perhaps the [vignette here](http://www.strengejacke.de/sjPlot/sjp.glmer/) helps you further?

There is only one line per predictor, because the predicted probabilities are based on the fixed effects *estimates*. Since each predictor has only one estimate, there's only one line. As the axis titles indicate, you have the predicted probabilities on the y-axis, and the values of each predictor on the x-axis. See `Details` in `?sjp.glmer`. An alternative approach to plot predicted probabilities is choosing `type = "eff"`.

**Comment by mattjerhart** [comment]
Turns out I was just looking for sj.int(). sjp.int(color_model,type='eff',swapPredictors=T,showCI=T,axisLimits.y=c(.57,.69)) did the trick. Is it possible to view a facet.grid of the interaction for each level of a random effect, e.g. subject? I'm having some difficulties setting line width with sjp.setTheme(). What's the best way to make arbitrary plot appearance changes with ggplot?

**Comment by sjPlot** [comment]
There's an argument `facet.grid`. See examples [in this vignette](http://strengejacke.de/sjPlot/sjp.int/).

> What's the best way to make arbitrary plot appearance changes with ggplot? 

You can, e.g., return the plot object to do further modifications. See [this vignette](http://www.strengejacke.de/sjPlot/custplot/), section _Further customization options_.

**Comment by sjPlot** [comment]
So, may I close this issue? If not, please reopen it.
