### ISSUE TITLE
Include data parameter in all plotting/table functions that work on vectors

### ISSUE THREAD

**Issue by jemus42** [sjPlot/devel#73]
Current usage:

```
sjp.xtab(dataframe$response, dataframe$group)
```

Proposed behavior (optionally):

```
sjp.xtab(data = dataframe, response, group)
```

Optionally, even a formula interface would be nice to have, especially for the *.xtab functions for example.

```
sjp.xtab(data = dataframe, formula = response ~ group)
```

The primary reason for this proposal is that ever since the expansion of the hadleyverse, more and more packages adopt the format of functions having a `data` object as the first argument so they work nicely with `dplyr` chains. Therefore, I am always mildly irritated that `sjPlot` seems to behave so much different then other packages I'm used to, and I would assume I am not the only person with that issue.

**Comment by sjPlot** [comment]
I'm considering a major overhaul of the package, pushing it towards major version 2.0
[This page](http://adv-r.had.co.nz/Computing-on-the-language.html) is very helpful to understand and implement NSE in order to evaluate function arguments, so I could make package functions work with the pipe operator. 

However, this would break backwards compatibility. But since my package is of a package type that is most likely not being imported by other packages, this might be no big deal...

**Comment by jemus42** [comment]
Breaking backwards compatibility would be a major step, but if you go for [semver](http://semver.org/), then it should at least be transparent bei bumping the major version.

In my opinion it would be justified if it meant the package would work nicely with `%>%`, I assume other people would agree.
