### ISSUE TITLE
Customize plot appearance with sjp.setTheme and ggplot2

### ISSUE THREAD

**Issue by trollius** [sjPlot/devel#83]
Hi Daniel,

thanks for great package! I just would like to report a bug which could be linked to an incompatibility with a newer version of ggplot2. 
When trying to set theme, I get a following error:
`> sjp.setTheme(theme = "bw")`
`Error: No geom called GeomJitter.`

Thanks a lot for any updates on this one,

**Comment by urspine** [comment]
Hi Anna, any solution regarding this? I think ggplot2 and sjplot sometimes clash with each other. I too have faced problems while running in rstudio presentation but not in regular rstudio command.

**Comment by trollius** [comment]
Hi Urspine, I tried to modify source code of the package but seems that this bug is something quite deep, so my debugging didn't result in a success :(

**Comment by sjPlot** [comment]
ggplot2 has had some major changes ([see here](https://github.com/hadley/ggplot2/blob/master/NEWS.md), unfortunately - since sjPlot is more or less a "wrapper" for ggplot2-functions - it affects many parts of the source code. Package maintainers of those packages that no longer work after the ggplot2-update have been asked to update their packages until Jan 26th. I'm working on this update and hopefully can submit it next week, so sjPlot will work as usual again...

**Comment by sjPlot** [comment]
@trollius It probably won't help "just" fixing `sjp.setTheme`, since many parts of the source code currently don't work with the new ggplot update. You can either wait for a sjPlot-update, or downgrade to ggplot 1.0.1 and wait befor upgrading to ggplot 2.0.0 until the sjPlot-update is submitted.

**Comment by urspine** [comment]
Thanks Daniel for the info! Looking forward to it.

**Comment by sjPlot** [comment]
Should be fixed now.
